version: '3.0'

services:
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./docker/db/dumps:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql

  php-fpm:
    build: ./docker/dockerfiles/php-fpm
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_DSN: ${DATABASE_DSN}
      URL_RULE_WITHOUT_STATUS: ${URL_RULE_WITHOUT_STATUS}
      URL_RULE_WITH_STATUS: ${URL_RULE_WITH_STATUS}
      APP_LANGUAGE: ${APP_LANGUAGE}
    ports:
      - "9000"
    volumes:
      - ./application:/usr/src/app

  nginx:
    image: nginx:1.25
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./docker/configuration_files/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./application/web:/usr/src/app/web
    depends_on:
      - php-fpm
