version: '3.0'

services:
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_manager
      MYSQL_USER: sergey
      MYSQL_PASSWORD: ks2905
    ports:
      - "3306"
    volumes:
      - ./docker/db/dumps:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/mysql

  php-cli:
    build: ./docker/dockerfiles/php-cli
    volumes:
      - ./:/usr/src/app

  php-fpm:
    build: ./docker/dockerfiles/php-fpm
    ports:
      - "9000"
    volumes:
      - ./:/usr/src/app

  nginx:
    image: nginx:1.25
    ports:
      - "8000:80"
    volumes:
      - ./docker/configuration_files/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - ./:/usr/src/app
    depends_on:
      - php-fpm
